export enum TileType {
  WALL = 'WALL',
  EMPTY = 'EMPTY',
  PELLET = 'PELLET',
  ENERGIZER = 'ENERGIZER',
  GHOST_HOUSE = 'GHOST_HOUSE',
  GATE = 'GATE',
}

export const MAP_WIDTH = 28;
export const MAP_HEIGHT = 36;

export const CHAR_TO_TILE_TYPE: Record<string, TileType> = {
  '#': TileType.WALL,
  W: TileType.WALL,
  '.': TileType.PELLET,
  o: TileType.ENERGIZER,
  O: TileType.ENERGIZER,
  '*': TileType.ENERGIZER,
  ' ': TileType.EMPTY,
  _: TileType.EMPTY,
  E: TileType.EMPTY,
  G: TileType.GHOST_HOUSE,
  H: TileType.GHOST_HOUSE,
  '-': TileType.GATE,
  '=': TileType.GATE,
};

export const RAW_MAP_DATA: readonly string[] = [
  '                            ',
  '                            ',
  '                            ',
  '############################',
  '#............##............#',
  '#.####.#####.##.#####.####.#',
  '#o####.#####.##.#####.####o#',
  '#.####.#####.##.#####.####.#',
  '#..........................#',
  '#.####.##.########.##.####.#',
  '#.####.##.########.##.####.#',
  '#......##....##....##......#',
  '######.##### ## #####.######',
  '     #.##### ## #####.#     ',
  '     #.##          ##.#     ',
  '     #.## ###--### ##.#     ',
  '######.## #GGGGGG# ##.######',
  '          #GGGGGG#          ',
  '######.## #GGGGGG# ##.######',
  '     #.## ######## ##.#     ',
  '     #.##          ##.#     ',
  '     #.## ######## ##.#     ',
  '######.## ######## ##.######',
  '#............##............#',
  '#.####.#####.##.#####.####.#',
  '#.####.#####.##.#####.####.#',
  '#o..##................##..o#',
  '###.##.##.########.##.##.###',
  '###.##.##.########.##.##.###',
  '#......##....##....##......#',
  '#.##########.##.##########.#',
  '#.##########.##.##########.#',
  '#..........................#',
  '############################',
  '                            ',
  '                            ',
];
